# Generated by Django 3.0.7 on 2020-11-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201031_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='price',
            new_name='starting_bid',
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Daily Essentials', 'Daily Essentials')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails'),
        ),
    ]
