# Generated by Django 3.0.7 on 2020-11-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201125_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Daily Essentials', 'Daily Essentials')], max_length=100, null=True),
        ),
    ]
