# Generated by Django 3.0.7 on 2020-11-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201125_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails'),
        ),
    ]
