# Generated by Django 3.1.5 on 2021-04-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduHub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='posts',
        ),
        migrations.AddField(
            model_name='course',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, to='eduHub.Post'),
        ),
    ]
